// Seeded 3D terrain: a forward (+X) height profile generated by a slope-walk
// (same idea as the 2D sim/terrain.ts), extruded laterally into a flat-across-Z
// ribbon. The collider is a trimesh built from the SAME vertices the renderer draws,
// so the physical floor is exactly the visible floor (a heightfield's row/col layout
// was ambiguous and let cars fall through). Pure data; no Rapier/React import.

import type { Rng } from './genome3d';

export interface Terrain3DOptions {
  /** 0..1 — how chaotic the forward slope walk is */
  roughness: number;
  /** 0..1 — clamp on per-step slope (cliff allowance) */
  maxSlope: number;
  /** forward subdivisions */
  segments?: number;
}

export interface Terrain3D {
  /** forward subdivisions (rows along +X) */
  nrows: number;
  /** per-row forward height profile in meters */
  profile: Float32Array;
  /** meters per forward subdivision */
  seg: number;
  /** forward length in meters */
  forwardLen: number;
  /** lateral width in meters */
  width: number;
}

const SEG = 2.5; // meters per forward subdivision
const NROWS_DEFAULT = 280; // → 700 m of track
const WIDTH = 30; // meters across
const LEAD_ROWS = 12; // flat lead so spawned cars don't drop onto a slope

/** Gentle-start difficulty ramp by forward distance (meters), echoing the 2D ramp. */
function ramp3d(x: number): number {
  if (x < 30) return 0.4;
  if (x < 140) return 0.4 + ((x - 30) / 110) * 0.6; // 0.4 → 1.0
  if (x < 450) return 1.0 + ((x - 140) / 310) * 0.2; // 1.0 → 1.2
  return 1.2;
}

export function generateTerrain3d(rng: Rng, opts: Terrain3DOptions): Terrain3D {
  const nrows = opts.segments ?? NROWS_DEFAULT;
  const forwardLen = nrows * SEG;

  const trendNoise = 0.18 + opts.roughness * 0.55;
  const slopeClamp = 0.35 + opts.maxSlope * 1.4;

  const profile = new Float32Array(nrows + 1);
  let h = 0;
  let slope = 0;
  for (let i = 0; i <= nrows; i++) {
    if (i >= LEAD_ROWS) {
      const x = (i - LEAD_ROWS) * SEG;
      const r = ramp3d(x);
      slope += (rng() - 0.5) * trendNoise * r;
      const cap = slopeClamp * r;
      if (slope > cap) slope = cap;
      if (slope < -cap) slope = -cap;
      h += slope * SEG * 0.32; // → meters, kept gentle for stability
    }
    profile[i] = h;
  }

  return { nrows, profile, seg: SEG, forwardLen, width: WIDTH };
}

/** Triangle-mesh data for the terrain ribbon, in absolute world coords (X ∈ [0,
 * forwardLen]). Used identically by the Rapier trimesh collider and the Three.js mesh,
 * so the physics floor is the visible floor. Two verts per row (z = ±width/2). */
export function terrainMeshData(t: Terrain3D): {
  vertices: Float32Array;
  indices: Uint32Array;
} {
  const halfW = t.width / 2;
  const rows = t.nrows;
  const vertices = new Float32Array((rows + 1) * 2 * 3);
  const indices = new Uint32Array(rows * 6);
  for (let i = 0; i <= rows; i++) {
    const x = i * t.seg;
    const y = t.profile[i];
    const base = i * 2 * 3;
    vertices[base + 0] = x;
    vertices[base + 1] = y;
    vertices[base + 2] = -halfW;
    vertices[base + 3] = x;
    vertices[base + 4] = y;
    vertices[base + 5] = halfW;
  }
  for (let i = 0; i < rows; i++) {
    const a = i * 2;
    const o = i * 6;
    indices[o + 0] = a;
    indices[o + 1] = a + 2;
    indices[o + 2] = a + 1;
    indices[o + 3] = a + 1;
    indices[o + 4] = a + 2;
    indices[o + 5] = a + 3;
  }
  return { vertices, indices };
}

/** Ground height (meters) at a forward world-X. Linear-interpolates the profile. */
export function sampleHeight3d(t: Terrain3D, worldX: number): number {
  const f = worldX / t.seg;
  if (f <= 0) return t.profile[0];
  if (f >= t.nrows) return t.profile[t.nrows];
  const i0 = Math.floor(f);
  const frac = f - i0;
  return t.profile[i0] * (1 - frac) + t.profile[i0 + 1] * frac;
}
