// Seeded 3D terrain: a forward (+X) height profile generated by a slope-walk (same idea
// as the 2D sim/terrain.ts), extruded laterally into a BANKED CHANNEL — a cross-axis
// vertex grid whose outer columns curl up into berms so cars are physically contained in
// the lane (no invisible walls). The collider is a trimesh built from the SAME vertices
// the renderer draws, so the physical floor is exactly the visible floor (a heightfield's
// row/col layout was ambiguous and let cars fall through). Pure data; no Rapier/React import.

import type { Rng } from './genome3d';

export interface Terrain3DOptions {
  /** 0..1 — how chaotic the forward slope walk is */
  roughness: number;
  /** 0..1 — clamp on per-step slope (cliff allowance) */
  maxSlope: number;
  /** full lateral width of the channel in meters (berms bank the outer portion) */
  trackWidth: number;
  /** forward subdivisions */
  segments?: number;
}

export interface Terrain3D {
  /** forward subdivisions (rows along +X) */
  nrows: number;
  /** lateral subdivisions (columns across ±Z) */
  ncols: number;
  /** per-row forward height profile (centerline) in meters */
  profile: Float32Array;
  /** meters per forward subdivision */
  seg: number;
  /** forward length in meters */
  forwardLen: number;
  /** full lateral width in meters (mesh spans ±trackWidth/2) */
  trackWidth: number;
}

const SEG = 2.5; // meters per forward subdivision
const NROWS_DEFAULT = 280; // → 700 m of track
const NCOLS = 9; // cross-axis vertices (odd → exact centerline column at z=0)
const LEAD_ROWS = 12; // flat lead so spawned cars don't drop onto a slope

// Banked-channel shape: the central FLAT_FRAC of the width is drivable-flat; outside it
// the ground curls up smoothly (cosine, no catchable lip) to BERM_HEIGHT at the edge.
const FLAT_FRAC = 0.5;
const BERM_HEIGHT = 3.5; // meters the outer edge rises

// Per-step slope decay — mean-reverts the slope walk so the track rolls (hills) instead
// of running away into a continuous climb/descent. Lower = gentler, more level terrain.
const SLOPE_DECAY = 0.9;

/** Extra height at a normalized lateral position u ∈ [-1, 1] (0 = centerline). */
function bermRaise(u: number): number {
  const a = Math.abs(u);
  if (a <= FLAT_FRAC) return 0;
  const t = (a - FLAT_FRAC) / (1 - FLAT_FRAC); // 0 at edge of flat → 1 at outer edge
  return BERM_HEIGHT * (1 - Math.cos(t * Math.PI)) * 0.5;
}

/** Difficulty ramp by forward distance (meters): rolling hills sooner, steep climbs late. */
function ramp3d(x: number): number {
  if (x < 30) return 0.4;
  if (x < 120) return 0.4 + ((x - 30) / 90) * 0.7; // 0.4 → 1.1
  if (x < 350) return 1.1 + ((x - 120) / 230) * 0.4; // 1.1 → 1.5
  return 1.5;
}

export function generateTerrain3d(rng: Rng, opts: Terrain3DOptions): Terrain3D {
  const nrows = opts.segments ?? NROWS_DEFAULT;
  const forwardLen = nrows * SEG;

  // Bumpier than before: bigger per-step drift, higher slope ceiling, and a larger
  // height factor so features actually read in 3D instead of looking like a flat plain.
  const trendNoise = 0.22 + opts.roughness * 0.8;
  const slopeClamp = 0.45 + opts.maxSlope * 1.9;

  const profile = new Float32Array(nrows + 1);
  let h = 0;
  let slope = 0;
  for (let i = 0; i <= nrows; i++) {
    if (i >= LEAD_ROWS) {
      const x = (i - LEAD_ROWS) * SEG;
      const r = ramp3d(x);
      // Mean-revert the slope toward 0 before adding noise — without this the slope
      // random-walk runs away and the track becomes one long plunge instead of
      // rolling hills. Decay bounds the slope so features undulate.
      slope = slope * SLOPE_DECAY + (rng() - 0.5) * trendNoise * r;
      const cap = slopeClamp * r;
      if (slope > cap) slope = cap;
      if (slope < -cap) slope = -cap;
      h += slope * SEG * 0.5; // → meters
    }
    profile[i] = h;
  }

  return { nrows, ncols: NCOLS, profile, seg: SEG, forwardLen, trackWidth: opts.trackWidth };
}

/** Triangle-mesh data for the banked channel, in absolute world coords (X ∈ [0,
 * forwardLen], Z ∈ [-trackWidth/2, +trackWidth/2]). Used identically by the Rapier trimesh
 * collider and the Three.js mesh, so the physics floor is the visible floor. An
 * (nrows+1) × ncols vertex grid; outer columns are raised by bermRaise. */
export function terrainMeshData(t: Terrain3D): {
  vertices: Float32Array;
  indices: Uint32Array;
} {
  const rows = t.nrows;
  const cols = t.ncols;
  const halfW = t.trackWidth / 2;
  const vertices = new Float32Array((rows + 1) * cols * 3);
  const indices = new Uint32Array(rows * (cols - 1) * 6);
  for (let r = 0; r <= rows; r++) {
    const x = r * t.seg;
    const baseH = t.profile[r];
    for (let c = 0; c < cols; c++) {
      const u = (c / (cols - 1)) * 2 - 1; // -1 .. 1 across the width
      const vi = (r * cols + c) * 3;
      vertices[vi + 0] = x;
      vertices[vi + 1] = baseH + bermRaise(u);
      vertices[vi + 2] = u * halfW;
    }
  }
  // Two triangles per grid quad. Winding (a,b,cc)/(b,d,cc) yields +Y (upward) normals
  // for this layout (+X = increasing row, +Z = increasing col) — verified by cross
  // product. Consistent upward winding is what keeps cars from falling through.
  let o = 0;
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols - 1; c++) {
      const a = r * cols + c; // this row, this col
      const b = a + 1; // this row, next col (+Z)
      const cc = a + cols; // next row (+X), this col
      const d = cc + 1; // next row, next col
      indices[o + 0] = a;
      indices[o + 1] = b;
      indices[o + 2] = cc;
      indices[o + 3] = b;
      indices[o + 4] = d;
      indices[o + 5] = cc;
      o += 6;
    }
  }
  return { vertices, indices };
}

/** Ground height (meters) at a forward world-X. Linear-interpolates the profile. */
export function sampleHeight3d(t: Terrain3D, worldX: number): number {
  const f = worldX / t.seg;
  if (f <= 0) return t.profile[0];
  if (f >= t.nrows) return t.profile[t.nrows];
  const i0 = Math.floor(f);
  const frac = f - i0;
  return t.profile[i0] * (1 - frac) + t.profile[i0 + 1] * frac;
}
